### ISSUE TITLE
Add bundle.js (output of transform) to README.md

### ISSUE THREAD

**Issue by zenflow** [dsdenes/browserify-cdnjs#1]
Looks potentially very useful, but I can't tell without (a) downloading & trying it or (b) digging in to the source code.
A simple print of the browserified script resulting from the example would go a long way to document what this package does.
Thanks for being open-source!

**Comment by dsdenes** [comment]
Thank you for your comment. I've added additional information about how does it work.

**Comment by zenflow** [comment]
You the man
